import { Property, Location, Testimonial, BlogPost } from './types'

const BUCKET_BASE =
  process.env.NEXT_PUBLIC_GCS_BUCKET_BASE ||
  'https://storage.googleapis.com/propabridge-listings-us'

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'PB-ABJ-0101',
    slug: '3-bedroom-terrace-identity-estate-karsana-north',
    title: '3-Bedroom Terrace House with BQ — The Identity Estate, Karsana North',
    shortDescription: 'A well-finished 3-bedroom terrace house with BQ in the prestigious Identity Estate.',
    fullDescription: 'Brand new 3-bedroom terrace house with BQ, all ensuite, fitted kitchen, and secure compound. Located inside the prestigious Identity Estate, Karsana North District — one of Abuja\'s fastest-growing residential addresses.',
    bodyParagraphs: [
      'This is a brand new 3-bedroom terrace house with BQ in Karsana North — finished to a contemporary standard and positioned inside the prestigious Identity Estate, one of Abuja\'s most secure and well-planned residential communities.',
      'Every bedroom is ensuite. The ground floor opens into a spacious living and dining area, with a fitted kitchen with modern cabinetry leading to the rear. A family lounge connects the upper level, giving you a comfortable secondary living space. The 1-room BQ handles staff or guest needs independently.',
      'Large windows throughout bring in natural light and give the interiors an open, airy feel. A perimeter fence and a dedicated security post ensure round-the-clock safety within the estate. Ample parking is available within the compound.',
      'The location speaks for itself — Karsana North is quiet, well-maintained, and within minutes of Airport Road, Life Camp, and major commercial hubs. This is the kind of address that holds its value.',
      'Verified by Propabridge — title documents and physical inspection confirmed before listing.',
    ],
    amenityTags: [
      'Park', 'School/university', 'Highway access', 'Terrace',
      'Near bus stop', 'Garden', 'Walk-in closet',
    ],
    amenities: [
      'Fully Fitted Kitchen', 'Boys\' Quarters', 'All Ensuite', 'Ample Parking',
      'Perimeter Fence', 'Security Post', '24/7 Estate Security', 'Paved Roads',
    ],
    features: [
      'All bedrooms ensuite',
      'Fitted kitchen — modern cabinetry',
      'Spacious main living room',
      'Family lounge — upper floor',
      '1-room self-contained BQ',
      'Perimeter fence and security post',
      '24/7 estate security',
      'Large windows — abundant natural light',
      'Contemporary architectural finishing',
      'Ample parking — on compound',
      'Secure, serene estate environment',
      'Brand new — never been occupied',
    ],
    condition: 'Brand New',
    water: 'Public (Estate Supply)',
    pricingBreakdown: {
      netRent: 160000000,
      cautionFee: 16000000,
      serviceCharge: 500000,
      agencyFeePercentage: 10,
      legalFeePercentage: 10,
      totalFirstYearCost: '₦176,500,000 + agency & legal fees',
    },
    location: 'THE IDENTITY ESTATE, KARSANA NORTH DISTRICT, ABUJA FCT',
    district: 'Karsana North',
    city: 'Abuja',
    state: 'FCT',
    price: 160000000,
    status: 'FOR SALE',
    type: 'Terrace',
    beds: 3,
    baths: 4,
    toilets: 4,
    area: 280,
    areaUnit: 'sqm',
    parkingSpaces: 2,
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    ],
    verified: true,
    verificationStatus: 'VERIFIED',
    verificationItems: ['Title Verified', 'Physically Inspected', 'Zero Inspection Fees'],
    titleDocumentAvailable: true,
    featured: true,
    createdAt: '2026-03-15T00:00:00Z',
    updatedAt: '2026-04-01T00:00:00Z',
  },
  {
    id: 'PB-ABJ-0102',
    slug: 'commercial-shop-promenade-mall-lokogoma',
    title: 'Commercial Shop — The Promenade Mall, Lokogoma, Abuja (From ₦16.8M)',
    shortDescription: 'Ground-floor commercial units in the newly opened Promenade Mall, Lokogoma.',
    location: 'LOKOGOMA DISTRICT, ABUJA FCT',
    district: 'Lokogoma',
    city: 'Abuja',
    state: 'FCT',
    price: 16800000,
    priceLabel: '₦16,800,000',
    areaLabel: '12–16 SQM (Units Available)',
    status: 'FOR SALE',
    type: 'Commercial',
    area: 14,
    areaUnit: 'sqm',
    images: [
      'https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=800&q=80',
    ],
    verified: true,
    verificationStatus: 'VERIFIED',
    verificationItems: ['Title Verified', 'Physically Inspected'],
    titleDocumentAvailable: true,
    featured: false,
    createdAt: '2026-03-20T00:00:00Z',
    updatedAt: '2026-04-02T00:00:00Z',
  },
  {
    id: 'PB-KD-0105',
    slug: 'millenium-city-kaduna-babban-saura-land',
    title: 'Millenium City, Kaduna — Babban Saura',
    shortDescription: 'Surveyed dry land plots in the fast-developing Millenium City estate off Yakowa Way.',
    location: 'BABBAN SAURA, MAKARFI ROAD, OFF YAKOWA WAY, KADUNA, KADUNA STATE',
    district: 'Babban Saura',
    city: 'Kaduna',
    state: 'Kaduna',
    price: 2500000,
    priceLabel: '₦2.5M\u2011₦8M',
    areaLabel: '450\u2011900 SQM',
    status: 'FOR SALE',
    type: 'Land',
    area: 450,
    areaUnit: 'sqm',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
    ],
    verified: true,
    verificationStatus: 'VERIFIED',
    verificationItems: ['Survey Plan Available', 'Title Verified'],
    titleDocumentAvailable: true,
    featured: true,
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-04-10T00:00:00Z',
  },
  {
    id: 'PB-ABJ-0106',
    slug: '5-bedroom-detached-efab-metropolis-karsana',
    title: '5-Bedroom Detached House with BQ — Efab Metropolis, Karsana',
    shortDescription: 'Fully detached 5-bedroom house with boys quarters in the prestigious Efab Metropolis estate.',
    location: 'KARSANA, ABUJA FCT',
    district: 'Karsana',
    city: 'Abuja',
    state: 'FCT',
    price: 450000000,
    status: 'FOR SALE',
    type: 'Detached',
    beds: 5,
    baths: 6,
    toilets: 7,
    area: 500,
    areaUnit: 'sqm',
    parkingSpaces: 3,
    floors: 2,
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    ],
    verified: true,
    verificationStatus: 'VERIFIED',
    verificationItems: ['Title Verified', 'Physically Inspected', 'Zero Inspection Fees'],
    titleDocumentAvailable: true,
    featured: true,
    createdAt: '2026-04-05T00:00:00Z',
    updatedAt: '2026-04-12T00:00:00Z',
  },

  {
    id: 'PB-ABJ-0103',
    slug: '4-bedroom-detached-maitama-abuja',
    title: '4-Bedroom Detached Duplex — Maitama District, Abuja',
    shortDescription: 'Elegant detached duplex in the heart of Maitama, with full fittings and BQ.',
    location: 'MAITAMA DISTRICT, ABUJA FCT',
    district: 'Maitama',
    city: 'Abuja',
    state: 'FCT',
    price: 420000000,
    status: 'FOR SALE',
    type: 'Detached',
    beds: 4,
    baths: 5,
    toilets: 6,
    area: 465,
    areaUnit: 'sqm',
    floors: 2,
    parkingSpaces: 3,
    images: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80',
    ],
    verified: true,
    verificationStatus: 'VERIFIED',
    verificationItems: ['Title Verified', 'Physically Inspected', 'Zero Inspection Fees'],
    titleDocumentAvailable: true,
    featured: true,
    createdAt: '2026-03-10T00:00:00Z',
    updatedAt: '2026-04-05T00:00:00Z',
  },
  {
    id: 'PB-KD-0104',
    slug: '3-bedroom-apartment-gra-kaduna',
    title: '3-Bedroom Apartment — GRA Phase 1, Kaduna',
    shortDescription: 'Fully serviced apartment in a secure compound in Kaduna GRA.',
    location: 'GRA PHASE 1, KADUNA',
    district: 'GRA',
    city: 'Kaduna',
    state: 'Kaduna',
    price: 45000000,
    status: 'FOR RENT',
    type: 'Apartment',
    beds: 3,
    baths: 3,
    area: 185,
    areaUnit: 'sqm',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    ],
    verified: true,
    verificationStatus: 'VERIFIED',
    verificationItems: ['Title Verified', 'Physically Inspected'],
    titleDocumentAvailable: true,
    featured: false,
    createdAt: '2026-02-28T00:00:00Z',
    updatedAt: '2026-04-01T00:00:00Z',
  },
]

export const MOCK_LOCATIONS: Location[] = [
  {
    id: 'gwarinpa',
    name: 'Gwarinpa',
    district: 'Gwarinpa Estate',
    city: 'Abuja',
    state: 'FCT',
    image: `${BUCKET_BASE}/neighborhoods/gwarinpa-abuja.jpg`,
    propertyCount: 42,
    description: 'One of Abuja\'s largest residential districts with a mix of housing types.',
  },
  {
    id: 'maitama',
    name: 'Maitama',
    district: 'Maitama',
    city: 'Abuja',
    state: 'FCT',
    image: `${BUCKET_BASE}/neighborhoods/maitama-abuja.jpg`,
    propertyCount: 28,
    description: 'Abuja\'s most prestigious district, home to embassies and high-end residences.',
  },
  {
    id: 'karsana',
    name: 'Karsana North',
    district: 'Karsana North',
    city: 'Abuja',
    state: 'FCT',
    image: `${BUCKET_BASE}/neighborhoods/karsana-abuja.jpg`,
    propertyCount: 15,
    description: 'A fast-growing residential district with modern estate developments.',
  },
  {
    id: 'asokoro',
    name: 'Asokoro',
    district: 'Asokoro',
    city: 'Abuja',
    state: 'FCT',
    image: `${BUCKET_BASE}/neighborhoods/asokoro-abuja.jpg`,
    propertyCount: 19,
    description: 'Government and diplomatic hub with upscale residential properties.',
  },
  {
    id: 'kaduna-city',
    name: 'Kaduna City',
    district: 'Central',
    city: 'Kaduna',
    state: 'Kaduna',
    image: `${BUCKET_BASE}/neighborhoods/kaduna-city.jpg`,
    propertyCount: 22,
    description: 'Northern Nigeria\'s commercial capital with diverse property options.',
  },
  {
    id: 'minna',
    name: 'Minna',
    district: 'Central',
    city: 'Minna',
    state: 'Niger',
    image: `${BUCKET_BASE}/neighborhoods/minna.jpg`,
    propertyCount: 11,
    description: 'Niger State\'s capital city with affordable housing opportunities.',
  },
]

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: 't01',
    name: 'Aisha Mahmoud',
    location: 'Bought in Karsana North, Abuja',
    stars: 5,
    quote: 'I was skeptical at first — I had been scammed before. But Propabridge showed me the title documents before I even visited. First time I felt safe searching for property online.',
    verified: true,
    type: 'Buyer',
    date: '2026-02-10',
  },
  {
    id: 't02',
    name: 'Chukwuemeka Obi',
    location: 'Diaspora Buyer — Purchased from the UK',
    stars: 5,
    quote: 'I bought a 3-bedroom flat in Abuja entirely through WhatsApp and the Propabridge platform. Zero fees. Zero stress. The team sent video verification and documents. I signed from London.',
    verified: true,
    type: 'Diaspora Buyer',
    date: '2026-01-28',
  },
  {
    id: 't03',
    name: 'Ibrahim Tanko',
    location: 'Rented in Gwarinpa, Abuja',
    stars: 5,
    quote: 'Every agent I contacted before wanted inspection fees upfront. Propabridge said zero fees and they meant it. Found my apartment in three days.',
    verified: true,
    type: 'Renter',
    date: '2026-03-05',
  },
]

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: 'b01',
    slug: 'abuja-real-estate-market-2026',
    title: 'Abuja Real Estate Market in 2026: What Buyers Need to Know',
    excerpt: 'Property prices in Abuja\'s key districts have shifted significantly this year. Here is what the data says and what it means for buyers.',
    content: '',
    category: 'Market Insight',
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=700&q=80',
    author: 'Propabridge Team',
    publishedAt: '2026-04-10',
    readTime: 5,
  },
  {
    id: 'b02',
    slug: 'guide-to-gwarinpa-abuja',
    title: 'Living in Gwarinpa: A Complete Neighbourhood Guide',
    excerpt: 'Gwarinpa is one of Abuja\'s largest residential estates. From schools to markets, here is everything you need to know before moving.',
    content: '',
    category: 'Neighbourhood Guide',
    image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=700&q=80',
    author: 'Propabridge Team',
    publishedAt: '2026-04-01',
    readTime: 7,
  },
  {
    id: 'b03',
    slug: 'understanding-certificate-of-occupancy-nigeria',
    title: 'Certificate of Occupancy: Your Complete Legal Guide for Nigerian Property',
    excerpt: 'The C of O is the most important document in any Nigerian property transaction. Here is what it means and why you must always demand one.',
    content: '',
    category: 'Legal Tips',
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=700&q=80',
    author: 'Propabridge Team',
    publishedAt: '2026-03-25',
    readTime: 6,
  },
]
